# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_label.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LabelForm(object):
    def setupUi(self, LabelForm):
        LabelForm.setObjectName("LabelForm")
        LabelForm.resize(400, 276)
        self.label = QtWidgets.QLabel(LabelForm)
        self.label.setGeometry(QtCore.QRect(170, 210, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.graphicsView = QtWidgets.QGraphicsView(LabelForm)
        self.graphicsView.setGeometry(QtCore.QRect(20, 10, 171, 192))
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayoutWidget = QtWidgets.QWidget(LabelForm)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(210, 10, 160, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.retranslateUi(LabelForm)
        QtCore.QMetaObject.connectSlotsByName(LabelForm)

    def retranslateUi(self, LabelForm):
        _translate = QtCore.QCoreApplication.translate
        LabelForm.setWindowTitle(_translate("LabelForm", "Form"))
        self.label.setText(_translate("LabelForm", "Label"))
